In [ ]:
#importing necessary library
from sklearn import datasets
#for loading iris dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
#to split training and testing data from the given dataset
from sklearn.naive_bayes import GaussianNB 
#assuming that the given features are under gaussian distribution
iris=datasets.load_iris() 
#a dictionary containing description and data as array is returned
class_list=iris.target_names 
#storing class names in a list
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['class']=iris.target
print(df)
print("class names =",iris.target_names)
print(df.columns)


     sepal length (cm)  sepal width (cm)  ...  petal width (cm)  class
0                  5.1               3.5  ...               0.2      0
1                  4.9               3.0  ...               0.2      0
2                  4.7               3.2  ...               0.2      0
3                  4.6               3.1  ...               0.2      0
4                  5.0               3.6  ...               0.2      0
..                 ...               ...  ...               ...    ...
145                6.7               3.0  ...               2.3      2
146                6.3               2.5  ...               1.9      2
147                6.5               3.0  ...               2.0      2
148                6.2               3.4  ...               2.3      2
149                5.9               3.0  ...               1.8      2

[150 rows x 5 columns]
class names = ['setosa' 'versicolor' 'virginica']
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
     

class 0---->setosa
----------
class 1 ---->versicolor
----
class 2 ---->virginica
----

# 1 feature
feature taken: sepal length

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df[['sepal length (cm)']],df['class'],random_state=0)
#splitting testing and training data
sol=GaussianNB()
sol.fit(x_train,y_train)
feature_1_pred=sol.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
print('Accuracy : %.2f'%accuracy_score(y_test,feature_1_pred))
print('Confusion matrix : \n',confusion_matrix(y_test,feature_1_pred))
print('Precision_score : %.2f'%precision_score(y_test,feature_1_pred,average='micro'))
print('Recall_score : %.2f'%recall_score(y_test,feature_1_pred,average='micro'))

Accuracy : 0.63
Confusion matrix : 
 [[11  2  0]
 [ 3  9  4]
 [ 0  5  4]]
Precision_score : 0.63
Recall_score : 0.63


# 2 feature

features taken : sepal_length,sepla_width

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df[['sepal length (cm)','sepal width (cm)']],df['class'],random_state=0)
#splitting testing and training data
sol=GaussianNB()
sol.fit(x_train,y_train)
feature_2_pred=sol.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
print('Accuracy : %.2f'%accuracy_score(y_test,feature_2_pred))
print('Confusion matrix : \n',confusion_matrix(y_test,feature_2_pred))
print('Precision_score : %.2f'%precision_score(y_test,feature_2_pred,average='micro'))
print('Recall_score : %.2f'%recall_score(y_test,feature_2_pred,average='micro'))

Accuracy : 0.76
Confusion matrix : 
 [[13  0  0]
 [ 0 12  4]
 [ 0  5  4]]
Precision_score : 0.76
Recall_score : 0.76


# 3 feature

features taken : sepal_length,sepla_width,petal length (cm)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df[['sepal length (cm)','sepal width (cm)','petal length (cm)']],df['class'],random_state=0)
#splitting testing and training data
sol=GaussianNB()
sol.fit(x_train,y_train)
feature_3_pred=sol.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
print('Accuracy : %.2f'%accuracy_score(y_test,feature_3_pred))
print('Confusion matrix : \n',confusion_matrix(y_test,feature_3_pred))
print('Precision_score : %.2f'%precision_score(y_test,feature_3_pred,average='micro'))
print('Recall_score : %.2f'%recall_score(y_test,feature_3_pred,average='micro'))

Accuracy : 0.87
Confusion matrix : 
 [[13  0  0]
 [ 0 13  3]
 [ 0  2  7]]
Precision_score : 0.87
Recall_score : 0.87


# 4 feature

features taken:all features

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']],df['class'],random_state=0)
#splitting testing and training data
sol=GaussianNB()
sol.fit(x_train,y_train)
feature_4_pred=sol.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
print('Accuracy : %.2f'%accuracy_score(y_test,feature_4_pred))
print('Confusion matrix : \n',confusion_matrix(y_test,feature_4_pred))
print('Precision_score : %.2f'%precision_score(y_test,feature_4_pred,average='micro'))
print('Recall_score : %.2f'%recall_score(y_test,feature_4_pred,average='micro'))

Accuracy : 1.00
Confusion matrix : 
 [[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
Precision_score : 1.00
Recall_score : 1.00
